### ISSUE TITLE
Minecraft 1.19.2 Replay Crashes while trying to render when leaving a server

### ISSUE THREAD

**Issue by S-Pika** [min2222/ReplayMod-Forge-Reborn#13]
ReplayMod-1.0.6.jar
Forge 43.2.11
The replay works perfectly when recorded in singleplayer 

Any length of recorded replay in multiplayer even with no other players on will cause a crash message to appear when leaving a server and then cancels the replay render

java.lang.IndexOutOfBoundsException: readerIndex(2) + length(120) exceeds writerIndex(89): PooledUnsafeDirectByteBuf(ridx: 2, widx: 89, cap: 89)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.77.Final.jar%23113!/:4.1.77.Final] {}
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.77.Final.jar%23113!/:4.1.77.Final] {}
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895) ~[netty-buffer-4.1.77.Final.jar%23113!/:4.1.77.Final] {}
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903) ~[netty-buffer-4.1.77.Final.jar%23113!/:4.1.77.Final] {}
	at com.replaymod.lib.com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readBytes(ByteBufNetInput.java:106) ~[ReplayMod-1.0.6.jar%23618!/:?] {re:classloading}
	at com.replaymod.lib.com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readString(ByteBufNetInput.java:244) ~[ReplayMod-1.0.6.jar%23618!/:?] {re:classloading}
	at com.replaymod.replaystudio.protocol.packets.PacketTeam.getName(PacketTeam.java:43) ~[ReplayMod-1.0.6.jar%23618!/:?] {re:classloading}
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:472) ~[ReplayMod-1.0.6.jar%23618!/:?] {re:classloading}
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:225) ~[ReplayMod-1.0.6.jar%23618!/:?] {re:classloading}
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:296) ~[ReplayMod-1.0.6.jar%23618!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

![MultiplayerReplayCrash](https://github.com/min2222/ReplayMod-Forge-Reborn/assets/109268122/2e95649b-63fe-4395-8f14-2c82f25290db)

**Comment by min2222** [comment]
hopefully it fixed
